# MOwNiT 
## Laboratorium
## Wybrane zagadnienia algebry liniowej, faktoryzacja
### Algebra liniowa w Julii
https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/index.html

In [2]:
using(LinearAlgebra)

In [3]:
methods(factorize)

# 11 methods for generic function "factorize":
[1] factorize(A::Union{DenseArray{T,2}, Base.ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) where T in LinearAlgebra at /home/szelemeh/Programs/julia-1.4.0/share/julia/stdlib/v1.4/LinearAlgebra/src/dense.jl:1197
[2] factorize(A::Adjoint) in LinearAlgebra at /home/szelemeh/Programs/julia-1.4.0/share/julia/stdlib/v1.4/LinearAlgebra/src/dense.jl:1272
[3] factorize(A::Transpose) in LinearAlgebra at /home/szelemeh/Programs/julia-1.4.0/share/julia/stdlib/v1.4/LinearAlgebra/src/dense.jl:1273
[4] factorize(A::LinearAlgebra.AbstractTriangular) in LinearAlgebra at /home/szelemeh/Programs/julia-1.4.0/share/julia/stdlib/v1.4/LinearAlgebra/src/triangular.jl:2633
[5] factorize(A::Union{Hermitian{Complex{Float64},#s662}, Hermitian{Float64,#s662}, Symmetric{Float64,#s662}} where #s662<:SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at /home/szelemeh/Programs/julia-1.4.0/share/julia/stdlib/v1.4/SparseArrays/src/linalg.jl:1518
[6] factorize(A::Union{Hermitian{T,S}, Symmetric{T,S}} where S where T) in LinearAlgebra at /home/szelemeh/Programs/julia-1.4.0/share/julia/stdlib/v1.4/LinearAlgebra/src/symmetric.jl:620
[7] factorize(A::Tridiagonal) in LinearAlgebra at /home/szelemeh/Programs/julia-1.4.0/share/julia/stdlib/v1.4/LinearAlgebra/src/lu.jl:552
[8] factorize(D::Diagonal) in LinearAlgebra at /home/szelemeh/Programs/julia-1.4.0/share/julia/stdlib/v1.4/LinearAlgebra/src/diagonal.jl:121
[9] factorize(A::Bidiagonal) in LinearAlgebra at /home/szelemeh/Programs/julia-1.4.0/share/julia/stdlib/v1.4/LinearAlgebra/src/bidiag.jl:836
[10] factorize(S::SymTridiagonal) in LinearAlgebra at /home/szelemeh/Programs/julia-1.4.0/share/julia/stdlib/v1.4/LinearAlgebra/src/ldlt.jl:166
[11] factorize(A::SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at /home/szelemeh/Programs/julia-1.4.0/share/julia/stdlib/v1.4/SparseArrays/src/linalg.jl:1488

In [4]:
#wiersze vs kolumny
x1=[1 2 2]

1×3 Array{Int64,2}:
 1  2  2

In [5]:
y1=[1 ;2 ;3]

3-element Array{Int64,1}:
 1
 2
 3

In [6]:
transpose(x1)

3×1 Transpose{Int64,Array{Int64,2}}:
 1
 2
 2

In [7]:
#iloczyn skalarny
dot(x1,y1)

11

 Długość wektora liczymy jako pierwiastek z jego iloczynu skalarnego 
$$ \lVert\mathbf{v}\rVert = \sqrt{\mathbf{v}\cdot \mathbf{v}}=\sqrt{\sum_{i=1}^nv_i^2}$$



#### Przykładowe dane

In [8]:
#losujemy macierz 3x3
A=rand(3,3)

3×3 Array{Float64,2}:
 0.891896  0.0661564  0.7839
 0.610017  0.902016   0.428022
 0.638614  0.964226   0.21714

In [9]:
#losujemy wektor x
x=rand(3)

3-element Array{Float64,1}:
 0.8905626670284226
 0.06927311864713515
 0.32282001697944507

In [10]:
# wyliczamy b
b=A*x

3-element Array{Float64,1}:
 1.051930841759031
 0.7439181617585627
 0.7056181365490364

### Sposoby rozwiązania Ax=b

In [11]:
#mozemy policzyc odwrotność macierzy i wymnożyć
# uwaga: nieefektywne!
inv(A) * b

3-element Array{Float64,1}:
 0.8905626670284212
 0.06927311864713542
 0.32282001697944596

In [12]:
#najlepiej używać zoptymalizowanego operatora "\""
x=A\b

3-element Array{Float64,1}:
 0.8905626670284215
 0.06927311864713558
 0.32282001697944623

 operator "\\" wybiera odpowiednią faktoryzację:
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#LinearAlgebra.factorize
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#man-linalg-factorizations-1
 


### Faktoryzacja LU

In [13]:
# W przypadku ogólnej macierzy kwadratowej jest to faktoryzacja LU z pivotem
Af=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.716019  1.0       0.0
 0.683955  0.934463  1.0
U factor:
3×3 Array{Float64,2}:
 0.891896  0.0661564   0.7839
 0.0       0.916857   -0.344147
 0.0       0.0         0.213462

In [14]:
# Macierz L
Af.L

3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.716019  1.0       0.0
 0.683955  0.934463  1.0

In [15]:
#Macierz U
Af.U

3×3 Array{Float64,2}:
 0.891896  0.0661564   0.7839
 0.0       0.916857   -0.344147
 0.0       0.0         0.213462

In [16]:
# wektor permulatacji 
Af.p

3-element Array{Int64,1}:
 1
 3
 2

In [34]:
# to jest spełnione
Af.L*Af.U==A[Af.p,:]

3×3 Array{Float64,2}:
 0.891896  0.0661564  0.7839
 0.638614  0.964226   0.21714
 0.610017  0.902016   0.428022

In [18]:
# mozemy zamienic macierz A na postać zfaktoryzowaną
A=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0       0.0
 0.716019  1.0       0.0
 0.683955  0.934463  1.0
U factor:
3×3 Array{Float64,2}:
 0.891896  0.0661564   0.7839
 0.0       0.916857   -0.344147
 0.0       0.0         0.213462

In [19]:
# i działać na niej operatorem \
# operator ten będzie wykorzytywał raz utworzony wynik faktoryzacji
A\b

3-element Array{Float64,1}:
 0.8905626670284215
 0.06927311864713558
 0.32282001697944623

In [20]:
# dla różnych prawych stron równania z tą samą macierzą
c=rand(3);
A\c

3-element Array{Float64,1}:
 0.15099452860896656
 0.3166451605570247
 0.5491844848040343

### Faktoryzacja QR


In [21]:
B=rand(10,5)

10×5 Array{Float64,2}:
 0.157956   0.680796  0.476059  0.222802  0.769459
 0.142598   0.424797  0.443208  0.138728  0.654347
 0.0576379  0.139381  0.586247  0.302703  0.37969
 0.613228   0.765293  0.68881   0.974254  0.602849
 0.773344   0.792177  0.168988  0.47747   0.339765
 0.815464   0.274746  0.39284   0.915257  0.668149
 0.797743   0.235955  0.561141  0.265342  0.173709
 0.440484   0.927434  0.739501  0.265119  0.48943
 0.679059   0.139144  0.722533  0.750244  0.818205
 0.518988   0.873811  0.707168  0.479381  0.854049

In [22]:
# W przypadku ogólnej macierzy prostokątnej wybierana jest faktoryzacja QR z pivotem
factorize(B)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
10×10 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.39691    -0.371212    0.154129   …  -0.322325   -0.332443   -0.507715
 -0.337532   -0.308162   -0.0280382      0.0300695   0.194521   -0.100706
 -0.195855   -0.201624   -0.118352       0.344137   -0.495306    0.106897
 -0.310967    0.153895    0.222306      -0.423337    0.185255   -0.121434
 -0.175261    0.475363    0.374992       0.246803    0.0148898  -0.0247742
 -0.344651    0.293961   -0.374339   …   0.276471   -0.417966   -0.037089
 -0.0896041   0.608615   -0.0907607     -0.391743   -0.218716   -0.0937419
 -0.252463    0.0728137   0.507689       0.505446    0.197564   -0.192004
 -0.422054    0.0696462  -0.571412       0.0972853   0.555529   -0.0704799
 -0.440544   -0.0997701   0.196939      -0.204469   -0.0399663   0.80827
R factor:
5×5 Array{Float64,2}:
 -1.93863  -1.42732  -1.61137   -1.68604   -1.51517
  0.0       1.10061   0.29703    0.245447   0.644684
  0.0       0.0   

- $Q$ to macierz  ortogonalna mxm, co oznacza, że  $Q^T*Q=Q*Q^T=I$ czyli $Q^{-1}=Q^T$ (odwracanie takich macierzy jest szybkie i nie generuje dodatkowych błędów !)
- $R$ to macierz postaci $\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} $ , gdzie $Rfactor$ jest macierzą trójkątną górną, a 0 to macierz zer o wymierze nx(m-n)

### Zastosowanie faktoryzacji do metody najmniejszych kwadratów

Jednym z zastosowań faktoryzacji QR jest użycie jej do metody najmniejszych kwadratów.

Przykład:

Obliczmy dopasowanie wielomianu $$f(x)=wsp_2*x^2+wsp_1*x+wsp_0$$ do punktów (1,1) (2,2) (3,4) (4, 4) (5,3) (6,0)

- Budujemy układ równań wg wzoru $$wsp_2x_i^2+wsp_1x_i+wsp_0=y_i$$:
$$wsp_2*1^2+wsp_1*1+wsp_0=1$$
$$wsp_2*2^2+wsp_1*2+wsp_0=2$$
$$wsp_2*3^2+wsp_1*3+wsp_0=4$$
$$wsp_2*4^2+wsp_1*4+wsp_0=4$$
$$wsp_2*5^2+wsp_1*5+wsp_0=3$$
$$wsp_2*6^2+wsp_1*6+wsp_0=0$$

- Układ ten  nie ma dokładnego rozwiązania. Możemy jednak znaleźć najlepsze przybliżenie, czyli takie $wsp_i$, które minimalizują odległość:

$$\sqrt{\sum_{i=1}^{6}{(y_i-f(x_i))^2}}=\lVert y-A*wsp\rVert$$





Jak użyć do tej mimalizacji faktoryzacji QR:

#### 1. Tworzymy macierz A na postawie $(x_i,y_i)$

In [23]:
A=zeros(6,3) 

6×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

 punkty $(x_i,y_i)$


In [24]:
x=[1; 2 ;3 ;4 ;5 ;6]
y=[1; 2; 4; 4; 3; 0]

6-element Array{Int64,1}:
 1
 2
 4
 4
 3
 0

In [25]:
A[:,1]=x.^2

6-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36

In [26]:
A[:,2]=x

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [27]:
A[:,3]=ones(6)

6-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [28]:
A

6×3 Array{Float64,2}:
  1.0  1.0  1.0
  4.0  2.0  1.0
  9.0  3.0  1.0
 16.0  4.0  1.0
 25.0  5.0  1.0
 36.0  6.0  1.0

#### 2. Dokonujemy faktoryzacji QR macierzy A 

In [29]:
 AF=factorize(A)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
6×6 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.0209657  -0.343313    0.838525   0.112335    -0.0400677  -0.405397
 -0.0838628  -0.521522    0.167705  -0.00636667   0.34634     0.756879
 -0.188691   -0.534625   -0.223607  -0.612934    -0.487947   -0.121617
 -0.335451   -0.382624   -0.33541    0.753648    -0.213523   -0.122449
 -0.524142   -0.0655178  -0.167705  -0.204705     0.705864   -0.390779
 -0.754765    0.416693    0.279508  -0.0419783   -0.310667    0.283364
R factor:
3×3 Array{Float64,2}:
 -47.697  -9.24587  -1.90788
   0.0    -2.34816  -1.43091
   0.0     0.0       0.559017
permutation:
3-element Array{Int64,1}:
 1
 2
 3

In [30]:
# można przetestować ortogonalność:
Transpose(AF.Q)*AF.Q

6×6 Array{Float64,2}:
  1.0           0.0           1.11022e-16  …   8.32667e-17   0.0
  0.0           1.0           9.71445e-17     -5.55112e-17  -1.249e-16
  1.11022e-16   9.71445e-17   1.0             -4.16334e-17   0.0
 -9.71445e-17   3.46945e-17   2.60209e-17     -9.88792e-17  -2.08167e-17
  8.32667e-17  -5.55112e-17  -4.16334e-17      1.0           0.0
  0.0          -1.249e-16     0.0          …   0.0           1.0

Mamy równanie:
$$A*wsp=y$$
Dla $A=QR$:
$$QR*wsp =y$$
Możemy obydwie strony wymnożyć z lewej przez $Q^T$:
$$R*wsp =Q^T y$$
$$\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} wsp= Q^T y$$

Poszukiwanym rozwiązaniem jest rozwiązanie równania będącego górną niezerową częścią:
$$Rfactor * wsp= Q^T y[1:n]$$
$$wsp=Rfactor \setminus Q^T y[1:n]$$

In [31]:
# implementacja powyższego (uwaga: w tym przykladzie nie jest potrzebna permutacja,
# bo wektor permutacji wynosi[1 2 3])
AF.R\((Transpose(AF.Q)*y)[1:3])

3-element Array{Float64,1}:
 -0.5714285714285727
  3.942857142857152
 -2.8000000000000163

Więcej informacji:
- http://www.math.uconn.edu/~leykekhman/courses/MATH3795/Lectures/Lecture_8_Linear_least_squares_orthogonal_matrices.pdf
- http://www.seas.ucla.edu/~vandenbe/133A/lectures/qr.pdf

W praktyce używamy tego algorytmu poprzez operator "\\", za którym jest on "schowany".

In [32]:
A \ y

3-element Array{Float64,1}:
 -0.5714285714285726
  3.942857142857151
 -2.8000000000000145

In [33]:
#sprawdzamy czy dostaliśmy dobre wspólczynniki
using Polynomials
polyfit(x,y, 2)

Poly(-2.8000000000000145 + 3.942857142857151*x - 0.5714285714285726*x^2)

Funkcja <a href="https://github.com/JuliaMath/Polynomials.jl/blob/ef129b779d08f791eb607e390ca9d31d8c08ead1/src/Polynomials.jl#L689-L707">
polyfit</a> używa własnie tej metody


### Zadania

#### Zadanie 1 
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x.
Nastepnie rozwiąż równanie Ax=b trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie funkcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy  od drugiego wywołania !

#### Zadanie 2
Policz współczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.

#### Zadanie 3

Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji. Przykładowe (ale nie jedyne!) tematy:

-    tworzenie pseudoinversji macierzy (http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

-   uzycie faktoryzacji QR do znajdowania wartości własnych (https://en.wikipedia.org/wiki/QR_algorithm)

-  zastosowanie faktoryzacji SVD - przykład zastosowania w uczeniu maszynowym https://blog.statsbot.co/singular-value-decomposition-tutorial-52c695315254


